// Code generated by Kitex v0.7.0. DO NOT EDIT.

package relationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	relation "github.com/lyujsally/MinTikTok-lyujsally/kitex_gen/relation"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	IsFollow(ctx context.Context, Req *relation.DouyinRelationIsfollowRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationIsfollowResponse, err error)
	GetFolloweeCount(ctx context.Context, Req *relation.DouyinRelationFolloweeCountRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFolloweeCountResponse, err error)
	GetFollowerCount(ctx context.Context, Req *relation.DouyinRelationFollowerCountRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFollowerCountResponse, err error)
	GetFriendsList(ctx context.Context, Req *relation.DouyinRelationGetFriendListRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationGetFriendListResponse, err error)
	Action(ctx context.Context, Req *relation.DouyinRelationActionRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationActionResponse, err error)
	GetFolloweeList(ctx context.Context, Req *relation.DouyinRelationFollowListRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFollowListResponse, err error)
	GetFollowerList(ctx context.Context, Req *relation.DouyinRelationFollowerListRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFollowerListResponse, err error)
	GetFriendList(ctx context.Context, Req *relation.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationServiceClient struct {
	*kClient
}

func (p *kRelationServiceClient) IsFollow(ctx context.Context, Req *relation.DouyinRelationIsfollowRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationIsfollowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IsFollow(ctx, Req)
}

func (p *kRelationServiceClient) GetFolloweeCount(ctx context.Context, Req *relation.DouyinRelationFolloweeCountRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFolloweeCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFolloweeCount(ctx, Req)
}

func (p *kRelationServiceClient) GetFollowerCount(ctx context.Context, Req *relation.DouyinRelationFollowerCountRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFollowerCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowerCount(ctx, Req)
}

func (p *kRelationServiceClient) GetFriendsList(ctx context.Context, Req *relation.DouyinRelationGetFriendListRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationGetFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendsList(ctx, Req)
}

func (p *kRelationServiceClient) Action(ctx context.Context, Req *relation.DouyinRelationActionRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Action(ctx, Req)
}

func (p *kRelationServiceClient) GetFolloweeList(ctx context.Context, Req *relation.DouyinRelationFollowListRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFolloweeList(ctx, Req)
}

func (p *kRelationServiceClient) GetFollowerList(ctx context.Context, Req *relation.DouyinRelationFollowerListRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowerList(ctx, Req)
}

func (p *kRelationServiceClient) GetFriendList(ctx context.Context, Req *relation.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *relation.DouyinRelationFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendList(ctx, Req)
}
